version: "3.7"
services:
  
  backend:
    container_name: doctor-backend
    environment:
      - ASPNETCORE_URLS=http://+:59147
    build:
      context: .
      dockerfile: Dockerfile.back
    ports:
      - "59147:59147"
    networks: 
      - default
  frontend:
    depends_on:
      - backend
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - BACKEND_URL=http://doctor-backend:59147
    build:
      context: .
      dockerfile: Dockerfile.front
    ports:
      - "5000:5000"
    networks: 
      - default