FROM mcr.microsoft.com/dotnet/core/sdk:3.0 AS build
WORKDIR /app

COPY ./AppointmentRazor ./AppointmentRazor
COPY ./AppointmentModel ./AppointmentModel
WORKDIR /app/AppointmentRazor
RUN dotnet restore
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/core/aspnet:3.0 AS runtime
WORKDIR /app
COPY --from=build /app/AppointmentRazor/out ./
ENTRYPOINT [ "dotnet", "AppointmentRazor.dll" ]